[package]
name = "tailored"
version = "0.1.0"
edition = "2024"
description = "tailorED - bespoke, zero-config, vim-like editor"
license = "MIT"

[dependencies]
anyhow = "1"
ignore = "0.4"
nucleo-matcher = "0.3"
ropey = "1.6"
ratatui = "0.29"
unicode-segmentation = "1"
unicode-width = "0.2"

[[bin]]
name = "tailored"
path = "src/main.rs"

[lib]
name = "tailored"
path = "src/lib.rs"
