/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  aux_sym__line_token1 = 3,
  anon_sym_COLON = 4,
  anon_sym_STAR = 5,
  anon_sym_EQ = 6,
  sym_mnemonic = 7,
  sym_directive_name = 8,
  sym_macro_name = 9,
  anon_sym_POUND = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_COMMA = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_SLASH = 20,
  anon_sym_AMP = 21,
  anon_sym_PIPE = 22,
  anon_sym_CARET = 23,
  anon_sym_TILDE = 24,
  sym_number = 25,
  sym_string = 26,
  sym_char = 27,
  sym__symbol = 28,
  sym_comment = 29,
  sym_source_file = 30,
  sym__line = 31,
  sym__statement = 32,
  sym_label = 33,
  sym_pc_assignment = 34,
  sym_instruction = 35,
  sym_directive = 36,
  sym_macro_call = 37,
  sym__operand_tok = 38,
  sym_identifier = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_pc_assignment_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__line_token1] = "_line_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [anon_sym_EQ] = "=",
  [sym_mnemonic] = "mnemonic",
  [sym_directive_name] = "directive_name",
  [sym_macro_name] = "macro_name",
  [anon_sym_POUND] = "#",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_TILDE] = "~",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym__symbol] = "_symbol",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_pc_assignment] = "pc_assignment",
  [sym_instruction] = "instruction",
  [sym_directive] = "directive",
  [sym_macro_call] = "macro_call",
  [sym__operand_tok] = "_operand_tok",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_pc_assignment_repeat1] = "pc_assignment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_mnemonic] = sym_mnemonic,
  [sym_directive_name] = sym_directive_name,
  [sym_macro_name] = sym_macro_name,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym__symbol] = sym__symbol,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_pc_assignment] = sym_pc_assignment,
  [sym_instruction] = sym_instruction,
  [sym_directive] = sym_directive,
  [sym_macro_call] = sym_macro_call,
  [sym__operand_tok] = sym__operand_tok,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_pc_assignment_repeat1] = aux_sym_pc_assignment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym__symbol] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_pc_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_call] = {
    .visible = true,
    .named = true,
  },
  [sym__operand_tok] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pc_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_mnemonic = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_mnemonic, 0},
  [1] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 14,
        '\r', 1,
        '!', 8,
        '"', 3,
        '#', 21,
        '$', 5,
        '%', 4,
        '&', 32,
        '\'', 9,
        '(', 24,
        ')', 25,
        '*', 16,
        '+', 29,
        ',', 28,
        '-', 30,
        '/', 31,
        ':', 15,
        ';', 85,
        '<', 22,
        '=', 17,
        '>', 23,
        '[', 26,
        ']', 27,
        '^', 34,
        '{', 12,
        '|', 33,
        '}', 13,
        '~', 35,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '.' ||
          lookahead == '@') ADVANCE(6);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(50);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(46);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(57);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(63);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(61);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(59);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(51);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(62);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(68);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(55);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(60);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(45);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('F' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('f' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 14,
        '\r', 1,
        '"', 3,
        '#', 21,
        '$', 5,
        '%', 4,
        '&', 32,
        '\'', 9,
        '(', 24,
        ')', 25,
        '*', 16,
        '+', 29,
        ',', 28,
        '-', 30,
        '/', 31,
        ';', 85,
        '<', 22,
        '=', 17,
        '>', 23,
        '[', 26,
        ']', 27,
        '^', 34,
        '{', 12,
        '|', 33,
        '}', 13,
        '~', 35,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '.' ||
          lookahead == '@') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(36);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 6:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 7:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(41);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 14,
        '\r', 1,
        '!', 8,
        '*', 16,
        '+', 7,
        ':', 15,
        ';', 85,
        '{', 12,
        '}', 13,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (lookahead == '.' ||
          lookahead == '@') ADVANCE(6);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(50);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(46);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(57);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(63);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(61);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(59);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(51);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(62);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(68);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(55);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(60);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(45);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(42);
      if (('F' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('f' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__line_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_mnemonic);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_directive_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_macro_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '\'') ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__symbol);
      ADVANCE_MAP(
        'A', 76,
        'a', 76,
        'R', 47,
        'r', 47,
        'S', 72,
        's', 72,
        'X', 71,
        'x', 71,
        'Y', 44,
        'y', 44,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__symbol);
      ADVANCE_MAP(
        'B', 49,
        'b', 49,
        'E', 79,
        'e', 79,
        'M', 48,
        'm', 48,
        'T', 83,
        't', 83,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__symbol);
      ADVANCE_MAP(
        'B', 67,
        'b', 67,
        'C', 73,
        'c', 73,
        'E', 65,
        'e', 65,
        'I', 69,
        'i', 69,
        'M', 56,
        'm', 56,
        'N', 54,
        'n', 54,
        'P', 58,
        'p', 58,
        'R', 70,
        'r', 70,
        'V', 73,
        'v', 73,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(49);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(52);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(77);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(80);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(81);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(64);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(64);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(48);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(75);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(82);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'K' ||
          lookahead == 'a' ||
          lookahead == 'k') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'S' ||
          lookahead == 'a' ||
          lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'B' ||
          lookahead == 'X' ||
          lookahead == 'b' ||
          lookahead == 'x') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'C' ||
          lookahead == 'S' ||
          lookahead == 'c' ||
          lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'I' ||
          lookahead == 'S' ||
          lookahead == 'i' ||
          lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'L' ||
          lookahead == 'R' ||
          lookahead == 'l' ||
          lookahead == 'r') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'a' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'C' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'c' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'C' ||
          lookahead == 'D' ||
          lookahead == 'I' ||
          lookahead == 'c' ||
          lookahead == 'd' ||
          lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'P' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'a' ||
          lookahead == 'p' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'C' ||
          lookahead == 'D' ||
          lookahead == 'I' ||
          lookahead == 'V' ||
          lookahead == 'c' ||
          lookahead == 'd' ||
          lookahead == 'i' ||
          lookahead == 'v') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__symbol);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(18);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__symbol);
      if (lookahead == 'A' ||
          lookahead == 'P' ||
          ('X' <= lookahead && lookahead <= 'Z') ||
          lookahead == 'a' ||
          lookahead == 'p' ||
          ('x' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'w')) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(85);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym__line_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_mnemonic] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym__symbol] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__line] = STATE(12),
    [sym__statement] = STATE(20),
    [sym_label] = STATE(17),
    [sym_pc_assignment] = STATE(20),
    [sym_instruction] = STATE(20),
    [sym_directive] = STATE(20),
    [sym_macro_call] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(5),
    [aux_sym__line_token1] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [sym_mnemonic] = ACTIONS(11),
    [sym_directive_name] = ACTIONS(13),
    [sym_macro_name] = ACTIONS(15),
    [sym__symbol] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__operand_tok] = STATE(5),
    [sym_identifier] = STATE(5),
    [aux_sym_pc_assignment_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [aux_sym__line_token1] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_POUND] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_TILDE] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_char] = ACTIONS(21),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__operand_tok] = STATE(10),
    [sym_identifier] = STATE(10),
    [aux_sym_pc_assignment_repeat1] = STATE(10),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [aux_sym__line_token1] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_TILDE] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [sym_string] = ACTIONS(27),
    [sym_char] = ACTIONS(27),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym__operand_tok] = STATE(7),
    [sym_identifier] = STATE(7),
    [aux_sym_pc_assignment_repeat1] = STATE(7),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [aux_sym__line_token1] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_AMP] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(31),
    [anon_sym_TILDE] = ACTIONS(31),
    [sym_number] = ACTIONS(31),
    [sym_string] = ACTIONS(31),
    [sym_char] = ACTIONS(31),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(33),
  },
  [STATE(5)] = {
    [sym__operand_tok] = STATE(8),
    [sym_identifier] = STATE(8),
    [aux_sym_pc_assignment_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [aux_sym__line_token1] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_TILDE] = ACTIONS(35),
    [sym_number] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_char] = ACTIONS(35),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(37),
  },
  [STATE(6)] = {
    [sym__operand_tok] = STATE(9),
    [sym_identifier] = STATE(9),
    [aux_sym_pc_assignment_repeat1] = STATE(9),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [aux_sym__line_token1] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_POUND] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_AMP] = ACTIONS(39),
    [anon_sym_PIPE] = ACTIONS(39),
    [anon_sym_CARET] = ACTIONS(39),
    [anon_sym_TILDE] = ACTIONS(39),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_char] = ACTIONS(39),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(41),
  },
  [STATE(7)] = {
    [sym__operand_tok] = STATE(8),
    [sym_identifier] = STATE(8),
    [aux_sym_pc_assignment_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [aux_sym__line_token1] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_TILDE] = ACTIONS(35),
    [sym_number] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_char] = ACTIONS(35),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(43),
  },
  [STATE(8)] = {
    [sym__operand_tok] = STATE(8),
    [sym_identifier] = STATE(8),
    [aux_sym_pc_assignment_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [aux_sym__line_token1] = ACTIONS(48),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_EQ] = ACTIONS(45),
    [anon_sym_POUND] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(45),
    [anon_sym_CARET] = ACTIONS(45),
    [anon_sym_TILDE] = ACTIONS(45),
    [sym_number] = ACTIONS(45),
    [sym_string] = ACTIONS(45),
    [sym_char] = ACTIONS(45),
    [sym__symbol] = ACTIONS(50),
    [sym_comment] = ACTIONS(48),
  },
  [STATE(9)] = {
    [sym__operand_tok] = STATE(8),
    [sym_identifier] = STATE(8),
    [aux_sym_pc_assignment_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [aux_sym__line_token1] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_TILDE] = ACTIONS(35),
    [sym_number] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_char] = ACTIONS(35),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(53),
  },
  [STATE(10)] = {
    [sym__operand_tok] = STATE(8),
    [sym_identifier] = STATE(8),
    [aux_sym_pc_assignment_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [aux_sym__line_token1] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_TILDE] = ACTIONS(35),
    [sym_number] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_char] = ACTIONS(35),
    [sym__symbol] = ACTIONS(25),
    [sym_comment] = ACTIONS(55),
  },
  [STATE(11)] = {
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [aux_sym__line_token1] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_POUND] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_AMP] = ACTIONS(57),
    [anon_sym_PIPE] = ACTIONS(57),
    [anon_sym_CARET] = ACTIONS(57),
    [anon_sym_TILDE] = ACTIONS(57),
    [sym_number] = ACTIONS(57),
    [sym_string] = ACTIONS(57),
    [sym_char] = ACTIONS(57),
    [sym__symbol] = ACTIONS(57),
    [sym_comment] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      sym_macro_name,
    ACTIONS(17), 1,
      sym__symbol,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      aux_sym__line_token1,
    STATE(17), 1,
      sym_label,
    ACTIONS(5), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    STATE(13), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(20), 5,
      sym__statement,
      sym_pc_assignment,
      sym_instruction,
      sym_directive,
      sym_macro_call,
  [43] = 12,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      aux_sym__line_token1,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      sym_mnemonic,
    ACTIONS(77), 1,
      sym_directive_name,
    ACTIONS(80), 1,
      sym_macro_name,
    ACTIONS(83), 1,
      sym__symbol,
    ACTIONS(86), 1,
      sym_comment,
    STATE(17), 1,
      sym_label,
    ACTIONS(65), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    STATE(13), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(20), 5,
      sym__statement,
      sym_pc_assignment,
      sym_instruction,
      sym_directive,
      sym_macro_call,
  [86] = 2,
    ACTIONS(91), 1,
      sym__symbol,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__line_token1,
      anon_sym_STAR,
      sym_mnemonic,
      sym_directive_name,
      sym_macro_name,
      sym_comment,
  [101] = 2,
    ACTIONS(95), 1,
      sym__symbol,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__line_token1,
      anon_sym_STAR,
      sym_mnemonic,
      sym_directive_name,
      sym_macro_name,
      sym_comment,
  [116] = 2,
    ACTIONS(99), 1,
      sym__symbol,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__line_token1,
      anon_sym_STAR,
      sym_mnemonic,
      sym_directive_name,
      sym_macro_name,
      sym_comment,
  [131] = 6,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      sym_macro_name,
    ACTIONS(101), 1,
      aux_sym__line_token1,
    ACTIONS(103), 1,
      sym_comment,
    STATE(21), 4,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_macro_call,
  [153] = 2,
    ACTIONS(107), 1,
      anon_sym_COLON,
    ACTIONS(105), 5,
      aux_sym__line_token1,
      sym_mnemonic,
      sym_directive_name,
      sym_macro_name,
      sym_comment,
  [164] = 1,
    ACTIONS(109), 5,
      aux_sym__line_token1,
      sym_mnemonic,
      sym_directive_name,
      sym_macro_name,
      sym_comment,
  [172] = 2,
    ACTIONS(101), 1,
      aux_sym__line_token1,
    ACTIONS(103), 1,
      sym_comment,
  [179] = 2,
    ACTIONS(111), 1,
      aux_sym__line_token1,
    ACTIONS(113), 1,
      sym_comment,
  [186] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [190] = 1,
    ACTIONS(117), 1,
      anon_sym_EQ,
  [194] = 1,
    ACTIONS(101), 1,
      aux_sym__line_token1,
  [198] = 1,
    ACTIONS(111), 1,
      aux_sym__line_token1,
  [202] = 1,
    ACTIONS(119), 1,
      aux_sym__line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 43,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 101,
  [SMALL_STATE(16)] = 116,
  [SMALL_STATE(17)] = 131,
  [SMALL_STATE(18)] = 153,
  [SMALL_STATE(19)] = 164,
  [SMALL_STATE(20)] = 172,
  [SMALL_STATE(21)] = 179,
  [SMALL_STATE(22)] = 186,
  [SMALL_STATE(23)] = 190,
  [SMALL_STATE(24)] = 194,
  [SMALL_STATE(25)] = 198,
  [SMALL_STATE(26)] = 202,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 1, 0, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pc_assignment, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 1),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pc_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pc_assignment_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pc_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pc_assignment, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 2, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 1, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asm6502(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
